//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ в накладной.
    /// </summary>
    // *** Start programmer edit section *** (ЗаказВНакладной CustomAttributes)

    // *** End programmer edit section *** (ЗаказВНакладной CustomAttributes)
    [AutoAltered()]
    [Caption("Заказ в накладной")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказВНакладнойE", new string[] {
            "Количество as \'Количество\'",
            "Вес as \'Вес\'",
            "Цена as \'Цена\'",
            "Сумма as \'Сумма\'",
            "Товар as \'Товар\'",
            "Товар.Название as \'Название\'"}, Hidden=new string[] {
            "Товар.Название"})]
    [MasterViewDefineAttribute("ЗаказВНакладнойE", "Товар", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    public class ЗаказВНакладной : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private double fВес;
        
        private double fЦена;
        
        private double fСумма;
        
        private IIS.АСУ_Склад.Товар fТовар;
        
        private IIS.АСУ_Склад.Накладная fНакладная;
        
        // *** Start programmer edit section *** (ЗаказВНакладной CustomMembers)

        // *** End programmer edit section *** (ЗаказВНакладной CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказВНакладной.Количество CustomAttributes)

        // *** End programmer edit section *** (ЗаказВНакладной.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказВНакладной.Количество Get start)

                // *** End programmer edit section *** (ЗаказВНакладной.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ЗаказВНакладной.Количество Get end)

                // *** End programmer edit section *** (ЗаказВНакладной.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказВНакладной.Количество Set start)

                // *** End programmer edit section *** (ЗаказВНакладной.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ЗаказВНакладной.Количество Set end)

                // *** End programmer edit section *** (ЗаказВНакладной.Количество Set end)
            }
        }
        
        /// <summary>
        /// Вес.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказВНакладной.Вес CustomAttributes)

        // *** End programmer edit section *** (ЗаказВНакладной.Вес CustomAttributes)
        public virtual double Вес
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказВНакладной.Вес Get start)

                // *** End programmer edit section *** (ЗаказВНакладной.Вес Get start)
                double result = this.fВес;
                // *** Start programmer edit section *** (ЗаказВНакладной.Вес Get end)

                // *** End programmer edit section *** (ЗаказВНакладной.Вес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказВНакладной.Вес Set start)

                // *** End programmer edit section *** (ЗаказВНакладной.Вес Set start)
                this.fВес = value;
                // *** Start programmer edit section *** (ЗаказВНакладной.Вес Set end)

                // *** End programmer edit section *** (ЗаказВНакладной.Вес Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказВНакладной.Цена CustomAttributes)

        // *** End programmer edit section *** (ЗаказВНакладной.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказВНакладной.Цена Get start)

                // *** End programmer edit section *** (ЗаказВНакладной.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (ЗаказВНакладной.Цена Get end)

                // *** End programmer edit section *** (ЗаказВНакладной.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказВНакладной.Цена Set start)

                // *** End programmer edit section *** (ЗаказВНакладной.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (ЗаказВНакладной.Цена Set end)

                // *** End programmer edit section *** (ЗаказВНакладной.Цена Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказВНакладной.Сумма CustomAttributes)

        // *** End programmer edit section *** (ЗаказВНакладной.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказВНакладной.Сумма Get start)

                // *** End programmer edit section *** (ЗаказВНакладной.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (ЗаказВНакладной.Сумма Get end)

                // *** End programmer edit section *** (ЗаказВНакладной.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказВНакладной.Сумма Set start)

                // *** End programmer edit section *** (ЗаказВНакладной.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (ЗаказВНакладной.Сумма Set end)

                // *** End programmer edit section *** (ЗаказВНакладной.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Заказ в накладной.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказВНакладной.Товар CustomAttributes)

        // *** End programmer edit section *** (ЗаказВНакладной.Товар CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        [NotNull()]
        public virtual IIS.АСУ_Склад.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказВНакладной.Товар Get start)

                // *** End programmer edit section *** (ЗаказВНакладной.Товар Get start)
                IIS.АСУ_Склад.Товар result = this.fТовар;
                // *** Start programmer edit section *** (ЗаказВНакладной.Товар Get end)

                // *** End programmer edit section *** (ЗаказВНакладной.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказВНакладной.Товар Set start)

                // *** End programmer edit section *** (ЗаказВНакладной.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (ЗаказВНакладной.Товар Set end)

                // *** End programmer edit section *** (ЗаказВНакладной.Товар Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.АСУ_Склад.Накладная.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказВНакладной.Накладная CustomAttributes)

        // *** End programmer edit section *** (ЗаказВНакладной.Накладная CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Накладная"})]
        public virtual IIS.АСУ_Склад.Накладная Накладная
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказВНакладной.Накладная Get start)

                // *** End programmer edit section *** (ЗаказВНакладной.Накладная Get start)
                IIS.АСУ_Склад.Накладная result = this.fНакладная;
                // *** Start programmer edit section *** (ЗаказВНакладной.Накладная Get end)

                // *** End programmer edit section *** (ЗаказВНакладной.Накладная Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказВНакладной.Накладная Set start)

                // *** End programmer edit section *** (ЗаказВНакладной.Накладная Set start)
                this.fНакладная = value;
                // *** Start programmer edit section *** (ЗаказВНакладной.Накладная Set end)

                // *** End programmer edit section *** (ЗаказВНакладной.Накладная Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказВНакладнойE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказВНакладнойE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказВНакладнойE", typeof(IIS.АСУ_Склад.ЗаказВНакладной));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ЗаказВНакладной.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЗаказВНакладной CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЗаказВНакладной CustomAttributes)
    public class DetailArrayOfЗаказВНакладной : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.АСУ_Склад.DetailArrayOfЗаказВНакладной members)

        // *** End programmer edit section *** (IIS.АСУ_Склад.DetailArrayOfЗаказВНакладной members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЗаказВНакладной by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЗаказВНакладной.
        /// </summary>
        public DetailArrayOfЗаказВНакладной(IIS.АСУ_Склад.Накладная fНакладная) : 
                base(typeof(ЗаказВНакладной), ((ICSSoft.STORMNET.DataObject)(fНакладная)))
        {
        }
        
        public IIS.АСУ_Склад.ЗаказВНакладной this[int index]
        {
            get
            {
                return ((IIS.АСУ_Склад.ЗаказВНакладной)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.АСУ_Склад.ЗаказВНакладной dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
